### ISSUE TITLE
behavior of Accept() changed

### ISSUE THREAD

**Issue by pmorjan** [mdlayher/vsock#21]
It seems that  fda437ecbf04836c30bfb8c397ca7383c5d01a7e changed the behavior of the Accept method of vsock listeners. Accept is no longer a blocking operation. You can no longer simply loop on Accept() like in the example below. Accept always fails with EWOULDBLOCK. The demo in cmd/vcsp also fails. Is this intended? Thanks.
```
for {
	c, err := l.Accept()
	if err != nil {
		panic(err) // resource temporarily unavailable
	}
	go func() { doSomething(c) }()
}
```

**Comment by mdlayher** [comment]
Are you using Go 1.11.x?  I haven't used this package myself in several months but I understand these changes were made to make integration with the runtime network poller possible.

/cc @aybabtme @mxpv

**Comment by mxpv** [comment]
Hey. Right, `Accept` is no longer blocking. Initially I did this changes because of https://github.com/mdlayher/vsock/issues/19

I think a correct approach of handling this would be check if returned error is [temporary](https://github.com/golang/go/blob/35f4ec152b44ae5fc83aaf68e2eb3aa1a778e5cd/src/net/net.go#L390). Here is an example: https://github.com/containerd/ttrpc/blob/f51df4475b76e0ab0315ee0684bef0703a070e6b/server.go#L92

**Comment by pmorjan** [comment]
I understand the motivation for this PR. However I think it is worth mentioning that it's not only a bug fix as the title suggests. It now behaves differently to the net package. My fault not  pointing that out earlier. Thanks.

**Comment by mdlayher** [comment]
Fixed as of https://github.com/mdlayher/vsock/pull/26.
